#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100 but display fizz for multiple of 3, buzz for multiple of 5 and fizzbuzz for multiple of 3 and 5
i=1
while [ $i -le 100 ]
do 
if [ $((i % 15)) -eq 0 ]
then
echo "FizzBuzz"
elif [ $((i % 3)) -eq 0 ]
then 
echo "Fizz"
elif [ $((i % 5)) -eq 0 ]
then 
echo "Buzz"
else 
echo "$i"
fi
i=$((i + 1))
done
