#!/usr/bin/env bash
# Display bad luck from china at 4, bad luch from japan st 9 and bad luch for italy at 17
i=1
while [ $i -le 20 ]
do 
echo "$i"
case $i in
4)
echo "bad luck from China"
;;
9)
echo "bad luck from Japan"
;;
17)
echo "bad luck from Italy"
;;
esac
i=$((i + 1))
done
